import {PhraseAndText} from "./phrases";

export const englishPhraseAndText: PhraseAndText = {
    LionKruegeryFem: "Lion Kruegery (Female)",
    CrownedChicken: "Crowned Chicken",
    JungleLion: "Jungle Lion",
    CanadianWolf: "Canadian Wolf",
    CrownedCrane: "Crowned Crane",
    EagleRaroh: "Eagle Raroh",
    DesertLionFem: "Desert Lion (Female)",
    RysOstrovid: "Lynx Ostrovid",
    BengalTiger: "Bengal Tiger",
    VeverickaFialonosa: "Squirrel Finlayson",
    LionKruegery: "Lion Kruegery",
    FenekFox: "Fennec Fox",
    OrycSouthAfrican: "South African Oryx",
    VodarkaJelenovita: "Water Deer",
    ZeriavStepny: "Steppe Crane",
    OrolSkalny: "Golden Eagle",
    ZeriavJaponsky: "Japanese Crane",
    LabutKosoroba: "Swan Black-Necked",
    PumaAmericka: "American Puma",
    TheKataLemur: "Kata Lemur",
    TheSteppeZebra: "Steppe Zebra",
    TheBlueAndYellowAra: "Blue and Yellow Ara",
    TheBrownMonkey: "Brown Monkey",
    TheSpottedLeopardMelanisticForm: "Spotted Leopard (Melanistic Form)",
    TheCanadianLynx: "Canadian Lynx",
    TheAfricanOstrich: "African Ostrich",
    TheAmericanJaguar: "American Jaguar",
    TheDomesticDonkey: "Domestic Donkey",
    TheCaracalLynx: "Caracal Lynx",
    TheSmallOtter: "Small Otter",
    TheBengalCat: "Bengal Cat",
    TheFoxMongoose: "Fox Mongoose",
    TheCloudedLeopard: "Clouded Leopard",
    TheRedBelliedCaracara: "Red-Bellied Caracara",
    TheShortTailedLidia: "Short-Tailed Lidia",
    TheWhiteCockatoo: "White Cockatoo",
    TheCapybara: "Capybara",
    TheSteppeServal: "Steppe Serval",
    TheSpottedGenet: "Spotted Genet",
    TheSquirrelMonkey: "Squirrel Monkey",
    TheConureParrot: "Conure Parrot",
    TheWaterDeer: "Water Deer",
    TheFennecFox: "Fennec Fox",
    TheRoyalMouse: "Royal Mouse",
    TheDesertLion: "Desert Lion",
    ElectricityWarning: "CAUTION, CAGES ARE UNDER ELECTRICAL VOLTAGE",
    FamilyWarning: "PLEASE FAMILIES WITH CHILDREN, STAY IN A GROUP IN FRONT OF THE TERMINAL",
    NoFeeding: "NO FEEDING ANIMALS UNLESS ALLOWED IN CERTAIN AREAS",
    NoHands: "NO PETTING AND PUTTING HANDS INTO CAGES",
    NoLeaning: "NO LEANING ON CAGES THROUGHOUT THE AREA",
    NoOwnAnimals: "NO ENTRY WITH PETS",
    NoRunning: "NO RUNNING THROUGHOUT THE AREA",
    NoShouting: "NO SHOUTING AND DISTURBING THE ANIMALS",
    NoSmoking: "NO SMOKING THROUGHOUT THE AREA",
    NoTransportationDevices: "STRICT PROHIBITION OF ENTRY ON ROLLER SKATES, BICYCLES, SCOOTERS, AND ELECTRIC SCOOTERS",
    SafeDistance: "PLEASE MAINTAIN A DISTANCE OF AT LEAST 1.5 m FROM CAGES",
    TicketOneTime: "CAUTION! THE TICKET IS ONE-TIME ONLY AFTER ENTERING THE AREA!",
    VisitingPolicyCaption: "Basic Safety Guidelines",
    VisitingPolicyTextFirst: "Safety measures are also enforced in the Park to ensure the safety of both animals\n" +
        "                    and visitors. There are enclosures, barriers, and supervision by qualified\n" +
        "                    staff. Thanks to safety measures in the Park, the risk of contact between animals\n" +
        "                    and visitors is minimized. It is also important to follow the guidelines and rules\n" +
        "                    to ensure a safe and healthy environment for everyone.",
    VisitingPolicyTextSecond: "Please stay on marked paths, do not put your hands or mobile devices into the animal enclosures, and\n" +
        "                    respect the distance from them. It is also important not to feed animals (unless allowed\n" +
        "                    with designated food) as their diet is carefully controlled.",
    VisitingPolicyTextThird: "If you have any further safety-related questions, please contact our staff. We hope you\n" +
        "                    enjoy your visit!",
    SchoolEmailWarning: "WE KINDLY ASK LARGER VISITING GROUPS TO NOTIFY US ON THE EMAIL ADDRESS BELOW",
    AdultsFare: "ADULTS",
    ChildrenFare: "CHILDREN FROM 3 TO 18 YEARS",
    ChildrenUnderThreeFare: "CHILDREN UNDER 3",
    FareCaption: "Entry Prices",
    InvalidFare: "HOLDERS OF ZŤP INVALIDITY CARD",
    InvalidFareNote: "PERSONS ARE REQUIRED TO PRESENT THEIR ZŤP CARD",
    InvalidFareSupport: "HOLDERS OF ZŤP CARD AND THEIR ESCORT",
    NoPrice: "FREE",
    StudentFare: "STUDENTS UNDER THE AGE OF 26",
    StudentFareNote: "PERSONS ARE REQUIRED TO PRESENT THEIR STUDENT ID",
    ContactInfoCaption: "Contact Info",
    December: "December",
    February: "February",
    March: "March",
    November: "November",
    OpeningHoursNoteHolidaysSummer: "* Open on state holidays",
    OpeningHoursNoteHolidaysWinter: "* Open on state holidays and Christmas",
    OpeningHoursNoteRegisterSummer: "* Entry open until 17:30",
    OpeningHoursNoteRegisterWinter: "* Entry open until 15:30",
    OpeningHoursWeekend: "Weekend",
    OpeningHoursWorkDays: "Tuesday - Friday",
    OpeningHoursCaption: "Opening Hours",
    MenuAnimals: "Animals",
    MenuContact: "Contact",
    MenuFares: "Fares",
    MenuName: "Menu",
    MenuOpeningHours: "Opening hours",
    MenuVisitingPolicy: "Visiting policy",
    WelcomeText: 'Welcome to the park with the largest population of felids in Europe!',
    MoreThan: 'More than',
    Units: 'individuals',
    Types: 'species',
    AllAnimalsButton: 'OUR BELOVED CHARGES',
    SocialMediaCaption: 'Social media',
    ContactFooter: 'Contact info',
    VisitingAddressFooter: 'Visiting address',
    AboutSectionCaption: 'About us',
    AboutSectionContent: 'Our park strives to provide exciting experiences for visitors of all age groups. \n\nWe also offer various fun activities for children, such as bounce houses, playgrounds, and animal feeding. We also have a souvenir shop where you can purchase mementos from your visit. Come and have an unforgettable day full of adventure!',
    ZooDescriptionCaption: 'Some things about our park',
    ZooDescriptionContent: 'Our park is an amazing place where you can discover various species of animals from all over the world. We have tigers, monkeys, zebras, and many other fascinating creatures here. It\'s a great place to spend time with your family and an opportunity to learn more about nature. Don\'t forget to bring your camera to capture unforgettable moments with our animals.\uD83D\uDCF8'
}