import {PhraseAndText} from "./phrases";

export const hungarianPhraseAndText: PhraseAndText = {
    Shortcuts: 'Gyorsbillentyűk',
    TheKataLemur: "Kata Lemur",
    TheSteppeZebra: "Sztyeppe Zebra",
    LionKruegeryFem: "Oroszlán Kruegery (Nőstény)",
    CrownedChicken: "Koronás Csirke",
    JungleLion: "Dzsungel Oroszlán",
    CanadianWolf: "Kanadai Farkas",
    CrownedCrane: "Koronás Daru",
    EagleRaroh: "Sas Raroh",
    DesertLionFem: "Sivatagi Oroszlán (Nőstény)",
    RysOstrovid: "Rys Ostrovid",
    BengalTiger: "Bengáli Tigris",
    VeverickaFialonosa: "Finlayson Vöröscsíkos Mókus",
    LionKruegery: "Kruegery Oroszlán",
    FenekFox: "Fenek Róka",
    OrycSouthAfrican: "Dél-afrikai Oryx",
    VodarkaJelenovita: "Vodarka Jelenovita",
    ZeriavStepny: "Steppe Daru",
    OrolSkalny: "Szirti Sas",
    ZeriavJaponsky: "Japán Daru",
    LabutKosoroba: "Kosoroba Hattyú",
    PumaAmericka: "Amerikai Puma",
    TheBlueAndYellowAra: "Kék-sárga Ara",
    TheBrownMonkey: "Barna Majom",
    TheSpottedLeopardMelanisticForm: "Pöttyös Leopárd (Melanisztikus Forma)",
    TheCanadianLynx: "Kanadai Hiúz",
    TheAfricanOstrich: "Afrikai Strucc",
    TheAmericanJaguar: "Amerikai Jaguár",
    TheDomesticDonkey: "Házi Szamár",
    TheCaracalLynx: "Karakál Hiúz",
    TheSmallOtter: "Kis Vidra",
    TheBengalCat: "Bengáli Macska",
    TheFoxMongoose: "Róka Manguszta",
    TheCloudedLeopard: "Felhős Leopárd",
    TheRedBelliedCaracara: "Vöröshasú Karakará",
    TheShortTailedLidia: "Rövidfarkú Lidia",
    TheWhiteCockatoo: "Fehér Kakadu",
    TheCapybara: "Kapibara",
    TheSteppeServal: "Sztyeppe Szevála",
    TheSpottedGenet: "Pöttyös Genet",
    TheSquirrelMonkey: "Mókus Majom",
    TheConureParrot: "Kanári Papagáj",
    TheWaterDeer: "Vízi Szarvas",
    TheRoyalMouse: "Királyi Egér",
    TheDesertLion: "Sivatagi Oroszlán",
    ElectricityWarning: "FIGYELEM, A KETRECEK ELEKTROMOS FESZÜLTSÉG ALATT ÁLLNAK",
    FamilyWarning: "KÉRJÜK, CSALÁDOK GYERMEKEKKEL TARTÓZKODJANAK EGY CSOPORTBAN A TERMINÁL ELŐTT",
    NoFeeding: "ÁLLATOK ETETÉSE TILOS, HA NINCS AZ EBBEN KIJELENTETT TERÜLETEKEN",
    NoHands: "TILOS AZ ÁLLATOK SIMOGATÁSA ÉS A KETRECEKBE VALÓ BELENYÚLÁS",
    NoLeaning: "TILOS AZ ÁLLATKETRECEKRE TÁMASZKODNI AZ EGÉSZ TERÜLETEN",
    NoOwnAnimals: "NEM ENGEDI AZ ÁLLATOKKAL VALÓ BELÉPÉST",
    NoRunning: "TILOS A SZALADGÁLÁS AZ EGÉSZ TERÜLETEN",
    NoShouting: "TILOS KIÁLLÍTANI ÉS ZAVARNI AZ ÁLLATOKAT",
    NoSmoking: "TILOS DOHÁNYZÁS AZ EGÉSZ TERÜLETEN",
    NoTransportationDevices: "SZIGORÚ BEJÁRÁSI TILALOM ROLLER SKATE-EN, KERÉKPÁROKON, ROLLEREKEN ÉS ELEKTROMOS ROLLEREKEN",
    SafeDistance: "KÉRJÜK, TARTSON LEGALÁBB 1,5 MÉTERES TÁVOLSÁGOT A KETRECEKTŐL",
    TicketOneTime: "FIGYELEM! A JEGY CSAK EGYSZERI, A TERÜLETRE VALÓ BELÉPÉS UTÁN!",
    VisitingPolicyCaption: "Alapvető Biztonsági Irányelvek",
    VisitingPolicyTextFirst: "A Parkban biztonsági intézkedések is érvényben vannak annak érdekében, hogy a\n" +
        "                    mind az állatok, mind a látogatók biztonságban legyenek. Vannak kerítések, korlátok, és\n" +
        "                    képzett személyzet felügyelete. A Parkban alkalmazott biztonsági intézkedéseknek köszönhetően a\n" +
        "                    látogatók és az állatok közötti érintkezés veszélye minimális. Fontos továbbá a\n" +
        "                    irányelvek és szabályok betartása azért, hogy mindenki számára biztonságos és egészséges\n" +
        "                    környezetet biztosítsunk.",
    VisitingPolicyTextSecond: "Kérem, maradjon a kijelölt utakon, ne tegye be a kezét vagy mobil eszközöket az\n" +
        "                    állatok ketreceibe, és tartsa be a távolságot tőlük. Fontos, hogy ne etesse az állatokat (kivéve,\n" +
        "                    ha kijelölt ételekkel megengedett), mivel azok étrendje gondosan ellenőrzött.",
    VisitingPolicyTextThird: "Ha további biztonsági kérdése van, kérjük, lépjen kapcsolatba munkatársainkkal. Reméljük,\n" +
        "                    hogy élvezni fogja látogatását!",
    SchoolEmailWarning: "KÉRJÜK, AZ ISKOLÁKAT ÉRTESÍTENI, HOGY JELEZZÉK ELŐRE LÁTOGATÁSUKAT AZ ALÁBBI EMAIL CÍMEN",
    AdultsFare: "FELNŐTTEK",
    ChildrenFare: "3-18 ÉVES GYEREKEK",
    ChildrenUnderThreeFare: "3 ÉV ALATTI GYEREKEK",
    FareCaption: "Belépési Árak",
    InvalidFare: "ZŤP FOGYATÉKOS KÁRTYÁVAL RENDELKEZŐK",
    InvalidFareNote: "A SZEMÉLYEKNEK BE KELL MUTATNIUK ZŤP KÁRTYÁJUKAT",
    InvalidFareSupport: "ZŤP KÁRTYÁVAL RENDELKEZŐK ÉS KÍSÉRŐIK",
    NoPrice: "INGYENES",
    StudentFare: "26 ÉV ALATTI DIÁKOK",
    StudentFareNote: "A SZEMÉLYEKNEK BE KELL MUTATNIUK DIÁKIGAZOLVÁNYUKAT",
    ContactInfoCaption: "Kapcsolat Információ",
    December: "December",
    February: "Február",
    March: "Március",
    November: "November",
    OpeningHoursNoteHolidaysSummer: "* Nyitva állami ünnepeken",
    OpeningHoursNoteHolidaysWinter: "* Nyitva állami ünnepeken és karácsonykor",
    OpeningHoursNoteRegisterSummer: "* Belépés nyitva 17:30-ig",
    OpeningHoursNoteRegisterWinter: "* Belépés nyitva 15:30-ig",
    OpeningHoursWeekend: "Hétvége",
    OpeningHoursWorkDays: "Kedd - Péntek",
    OpeningHoursCaption: "Nyitvatartási Idők",
    MenuAnimals: "Állatok",
    MenuContact: "Kapcsolat",
    MenuFares: "Árak",
    MenuName: "Menü",
    MenuOpeningHours: "Nyitvatartási idők",
    MenuVisitingPolicy: "Látogatási szabályok",
    WelcomeText: 'Üdvözöljük a parkban, amelynek Európa legnagyobb félőspopulációjával rendelkezik!',
    MoreThan: 'Több mint',
    Units: 'egyedek',
    Types: 'fajok',
    AllAnimalsButton: 'SZERETETT VILÁGOK',
    SocialMediaCaption: 'Közösségi média',
    ContactFooter: 'Kapcsolat információ',
    VisitingAddressFooter: 'Látogatási cím',
    AboutSectionCaption: 'Rólunk',
    AboutSectionContent: 'Parkunk igyekszik izgalmas élményeket nyújtani minden korosztály számára. \n\nKülönféle szórakoztató tevékenységeket is kínálunk a gyerekek számára, mint például ugrálóvárak, játszóterek és állatetetés. Emellett ajándéküzletünkben emléktárgyakat is vásárolhat látogatása emlékére. Gyere el és töltődj fel egy felejthetetlen kalandokkal teli nap erejéig!',
    ZooDescriptionCaption: 'Néhány dolog rólunk',
    ZooDescriptionContent: 'Parkunk egy fantasztikus hely, ahol felfedezhet különböző állatfajokat az egész világról. Nálunk tigrisek, majmok, zebrák és sok más lenyűgöző lény található. Ez egy nagyszerű hely a családoddal való időtöltésre és egy lehetőség a természet megismerésére. Ne felejtsd el magaddal hozni a fényképezőgépedet, hogy megörökíthesd az állatainkkal való felejthetetlen pillanatokat.\uD83D\uDCF8'
}
