export type Phrase =
    'WelcomeText' |
    'MoreThan' |
    'Units' |
    'Types' |
    'AllAnimalsButton' |
    'SocialMediaCaption' |
    'ContactFooter' |
    'VisitingAddressFooter' |
    'AboutSectionCaption' |
    'AboutSectionContent' |
    'ZooDescriptionCaption' |
    'ZooDescriptionContent' |
    'MenuName' |
    'MenuOpeningHours' |
    'MenuContact' |
    'MenuAnimals' |
    'MenuFares' |
    'MenuVisitingPolicy' |
    'OpeningHoursCaption' |
    'OpeningHoursWorkDays' |
    'OpeningHoursWeekend' |
    'OpeningHoursNoteHolidaysSummer' |
    'OpeningHoursNoteRegisterSummer' |
    'OpeningHoursNoteRegisterWinter' |
    'OpeningHoursNoteHolidaysWinter' |
    'March' |
    'November' |
    'December' |
    'February' |
    'ContactInfoCaption' |
    'FareCaption' |
    'AdultsFare' |
    'ChildrenUnderThreeFare' |
    'ChildrenFare' |
    'StudentFare' |
    'StudentFareNote' |
    'InvalidFare' |
    'InvalidFareNote' |
    'InvalidFareSupport' |
    'NoPrice' |
    'SchoolEmailWarning' |
    'NoFeeding' |
    'NoHands' |
    'NoShouting' |
    'NoLeaning' |
    'SafeDistance' |
    'ElectricityWarning' |
    'NoRunning' |
    'NoSmoking' |
    'NoOwnAnimals' |
    'TicketOneTime' |
    'FamilyWarning' |
    'NoTransportationDevices' |
    'VisitingPolicyCaption' |
    'VisitingPolicyTextFirst' |
    'VisitingPolicyTextSecond' |
    'VisitingPolicyTextThird' |
    'TheKataLemur' |
    'TheSteppeZebra' |
    'TheBlueAndYellowAra' |
    'TheBrownMonkey' |
    'TheSpottedLeopardMelanisticForm' |
    'TheCanadianLynx' |
    'TheAfricanOstrich' |
    'TheAmericanJaguar' |
    'TheDomesticDonkey' |
    'TheCaracalLynx' |
    'TheSmallOtter' |
    'TheBengalCat' |
    'TheFoxMongoose' |
    'TheCloudedLeopard' |
    'TheRedBelliedCaracara' |
    'TheShortTailedLidia' |
    'TheWhiteCockatoo' |
    'TheCapybara' |
    'TheSteppeServal' |
    'TheSpottedGenet' |
    'TheSquirrelMonkey' |
    'TheConureParrot' |
    'TheWaterDeer' |
    'TheRoyalMouse' |
    'TheDesertLion' |
    'CrownedChicken' |
    'JungleLion' |
    'CanadianWolf' |
    'CrownedCrane' |
    'EagleRaroh' |
    'DesertLionFem' |
    'RysOstrovid' |
    'BengalTiger' |
    'VeverickaFialonosa' |
    'LionKruegery' |
    'LionKruegeryFem' |
    'FenekFox' |
    'OrycSouthAfrican' |
    'VodarkaJelenovita' |
    'ZeriavStepny' |
    'OrolSkalny' |
    'ZeriavJaponsky' |
    'LabutKosoroba' |
    'PumaAmericka' |
    'Shortcuts'


export type PhraseAndText = Record<Phrase, string>;