import {PhraseAndText} from "./phrases";

export const slovakPhraseAndText: PhraseAndText = {
    TheKataLemur: "Lemur Kata",
    TheSteppeZebra: "Zebra Stepná",
    TheBlueAndYellowAra: "Ara Modro-žltá",
    TheBrownMonkey: "Malpa Hnedá",
    TheSpottedLeopardMelanisticForm: "Leopard Škvrnitý ( melanistická forma)",
    TheCanadianLynx: "Rys Kanadský",
    TheAfricanOstrich: "Pštros africký",
    TheAmericanJaguar: "Jagúar Americký",
    TheDomesticDonkey: "Somár domáci",
    TheCaracalLynx: "Rys Karakal",
    TheSmallOtter: "Vydra Malá",
    TheBengalCat: "Mačka Bengálska",
    TheFoxMongoose: "Mangusta Líščia",
    TheCloudedLeopard: "Leopard obláčikový",
    TheRedBelliedCaracara: "Karakara červenobruchá",
    TheShortTailedLidia: "Ladniak krátkochvostý",
    TheWhiteCockatoo: "Kakadu biely",
    TheCapybara: "Kapybara",
    TheSteppeServal: "Serval Stepný",
    TheSpottedGenet: "Ženetka Škvrnitá",
    TheSquirrelMonkey: "Saimiri Vevericovitý",
    TheConureParrot: "Korela",
    TheWaterDeer: "Vodarka Jeleňovitá",
    TheFennecFox: "Lidla Fenek",
    TheRoyalMouse: "Myšiak Kráľovsky",
    TheDesertLion: "Lev Pustovy",
    ElectricityWarning: "POZOR, KLIETKY SÚ POD ELEKTRICKÝM NAPÄTÍM",
    FamilyWarning: "PROSÍME RODINY S ĎETMI, ABY SA ZDRŽIAVALI V SKUPINE PRED TERMINÁLOM",
    NoFeeding: "ZÁKAZ KŔMENIA ZVIERAT, POKIAĽ TO NIE JE POVOLENÉ NA URČITÝCH MIESTACH",
    NoHands: "ZÁKAZ HLADKANIA A VKLADANIA RÚK DO KLIETOK",
    NoLeaning: "ZÁKAZ OPIERANIA SA O KLIETKY V CELOM AREÁLI",
    NoOwnAnimals: "ZÁKAZ VSTUPU S DOMÁCIMI ZVIERATAMI",
    NoRunning: "ZÁKAZ BEHANIA PO CELOM AREÁLI",
    NoShouting: "ZÁKAZ KRIČAŤ A BUDIŤ ZVIERATÁ",
    NoSmoking: "ZÁKAZ FAJČIŤ V CELOM AREÁLI",
    NoTransportationDevices: "PRÍSNY ZÁKAZ VSTUPU V KORČULIACH, NA BICYKLOCH, KOLOBEŽKÁCH A EL. KOLOBEŽKÁCH",
    SafeDistance: "PROSÍM, DODRŽUJTE ODSTUP OD KLIETOK NAJMENEJ 1.5 m",
    TicketOneTime: "POZOR! LÍSTOK JE PO VSTUPE DO AREÁLU JEDNORÁZOVÝ!",
    VisitingPolicyCaption: "Základné bezpečnostné pokyny",
    VisitingPolicyTextFirst: "V Parku sa tiež uplatňujú bezpečnostné opatrenia, aby sa zabezpečilo, že\n" +
        "                    zvieratá a návštevníci sú v bezpečí. Existujú ohrady, zábrany a dozor zo strany kvalifikovaného\n" +
        "                    personálu. Vďaka bezpečnostným opatreniam v Parku sa minimalizuje riziko kontaktu medzi zvieratami a\n" +
        "                    návštevníkmi. Je tiež dôležité dodržiavať pokyny a pravidlá, aby sme zabezpečili bezpečné a zdravé\n" +
        "                    prostredie pre všetkých.",
    VisitingPolicyTextSecond: "Držte sa vyznačených chodníkov, nevkladajte ruky ani mobilné zariadenia do výbehov zvierat a\n" +
        "                    rešpektujte vzdialenosť od nich. Tiež je dôležité nekŕmiť zvieratá (pokiaľ to nie je povolené\n" +
        "                    vyhradeným jedlom), pretože ich strava je starostlivo kontrolovaná.",
    VisitingPolicyTextThird: " Ak máte nejaké ďalšie otázky týkajúce sa bezpečnosti, kontaktujte prosím personál. Dúfame, že\n" +
        "                    si užijete svoju návštevu!",
    SchoolEmailWarning: "POPROSÍME ŠKOLY, ABY PRÍCHOD HLÁSILIVOPRED NA NÁŠ MAIL",
    NoPrice: "ZDARMA",
    AdultsFare: "DOSPELÍ OD 18 ROKOV",
    ChildrenFare: "OD 3 DO 18 ROKOV",
    ChildrenUnderThreeFare: "DETI DO 3 ROKOV",
    FareCaption: "Cena vstupu",
    InvalidFare: "DRŽITEĽIA PREUKAZU ZŤP",
    InvalidFareNote: "PO PREDLOŽENÍ DOKLADU O ZŤP",
    InvalidFareSupport: "DRŽITEĽIA PREUKAZU ZŤP-S",
    StudentFare: "ŠTUDENTSKÝ DO 26 ROKOV",
    StudentFareNote: "S PLATNÝM DOKLADOM O ŠTÚDIU, ISIC-ZVÝHODNENÁ CENA",
    ContactInfoCaption: "Kontaktné informácie",
    December: "December",
    February: "Február",
    March: "Marec",
    November: "November",
    OpeningHoursNoteHolidaysSummer: "* Otvorené aj cez sviatky",
    OpeningHoursNoteHolidaysWinter: "* Otvorené aj cez sviatky, vrátane Vianoc",
    OpeningHoursNoteRegisterSummer: "* Kasa otvorená do 17:30",
    OpeningHoursNoteRegisterWinter: "* Kasa otvorená do 15:30",
    OpeningHoursWeekend: "Víkend",
    OpeningHoursWorkDays: "Pracovné dni",
    OpeningHoursCaption: "Otváracie hodiny",
    MenuAnimals: "Zvieratá",
    MenuContact: "Kontakt",
    MenuFares: "Cenník",
    MenuName: "Menu",
    MenuOpeningHours: "Otváracie hodiny",
    MenuVisitingPolicy: "Návštevný poriadok",
    WelcomeText: 'Vitajte v parku s najväčším množstvom mačkovitých šeliem v Európe!',
    MoreThan: 'Viac ako',
    Units: 'jedincov',
    Types: 'druhov',
    AllAnimalsButton: 'NAŠI ZVERENCI',
    SocialMediaCaption: 'Sociálne siete',
    ContactFooter: 'Kontaktné info',
    VisitingAddressFooter: 'Návštevnícka adresa',
    AboutSectionCaption: 'O nás',
    AboutSectionContent: 'Náš park sa snaží poskytovať vzrušujúce zážitky pre návštevníkov všetkých vekových skupín. \n\nTaktiež ponúka rôzne zábavné aktivity pre deti, ako sú skákacie hrady, preliezky a kŕmenie zvierat. Máme tiež obchod so suvenírmi, kde si môžete kúpiť pamiatky zo svojej návštevy. Príďte a zažite nezabudnuteľný deň plný dobrodružstva!',
    ZooDescriptionCaption: 'Niečo o našom parku',
    ZooDescriptionContent: 'Náš park je úžasné miesto, kde môžete objaviť rôzne druhy zvierat z celého sveta. Máme tu tigre, opice, zebry a mnoho ďalších fascinujúcich tvorov. Je to skvelé miesto na strávenie času s rodinou a možnosť naučiť sa viac o prírode. Nezabudnite si so sebou priniesť fotoaparát, aby ste zachytili nezabudnuteľné momenty s našimi zvieratami\uD83D\uDCF8'
}